```yaml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Build Docker image
      run: |
        docker build -t resume-ai .
        docker images

    - name: Run Docker image
      run: |
        docker run -d -p 8080:8080 --name resume-ai resume-ai
        docker ps

    - name: Test API with curl
      run: |
        sleep 10
        curl http://localhost:8080

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag resume-ai:latest ${{ secrets.DOCKER_USERNAME }}/resume-ai:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/resume-ai:latest

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "resume-ai"
        heroku_email: "your.email@example.com"
        usedocker: true
```
